name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - '6379:6379'
        options: --entrypoint redis-server
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.13.0
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install Bundler
      run: gem install bundler
    - name: Install Danger
      run: gem install danger -v 7.0.1
    - name: Execute Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: danger
    - name: Install sqlite3
      run: sudo apt-get install libsqlite3-dev
    - name: Install Ruby Dependencies
      run: |
        bundle --version
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      run: bundle exec rake
